pipeline
        {
            parameters
            {
                // Define DRIVER parameter for running the test
                choice(name: 'DRIVER', description: 'Choose browser', choices: 'chrome\nfirefox\nheadless')

                // Define test path to run
                string(name: 'TESTS_TO_RUN', defaultValue: 'tests/test_purchase_tickets.py', description: 'choose test to run')
            }

            options
            {
                // keep last 100 builds
                buildDiscarder(logRotator(numToKeepStr: '100'))

                // add timestamp
                timestamps()
            }
            agent any // run the pipeline on any available node
            stages
            {
                stage('SCM: code update') {
            steps {
              checkout([$class: 'GitSCM', 
                branches: [[name: '*/master']],
                doGenerateSubmoduleConfigurations: false,
                extensions: [[$class: 'CleanCheckout']],
                submoduleCfg: [], 
                userRemoteConfigs: [[url: 'https://github.com/anvesh519/selenium-docker-allure.git']]])
               bat "git status"
          }
                }
                stage('Docker build')
                {
                    steps
                    {
                        script
                        {
                            // copying and building selenium base
                            bat "copy selenium-base-image/Dockerfile ."
                            docker.build("selenium/standalone-chrome")

                            // copying and building selenium image
                            bat "copy selenium-automation-run/Dockerfile ."
                            docker.build("blazemeter/selenium_image")
                        }
                    }
                }
                stage('Run test')
                {
                    steps
                    {
                        script
                        {
                            try
                            {
                                // creating timestamp
                                def now = new Date()
                                tstamp = now.format("yyyyMMdd-HH:mm:ss.SSSS", TimeZone.getTimeZone('UTC'))

                                // running selenium tests using pytest via docker
                                bat "docker run " +
                                        "--privileged " +                           // The --privileged flag gives all capabilities to the container,
                                        "--shm-size=1g " +                          // shared memory size is set to 1G to prevent chromedriver memory leak
                                        "--rm " +                                   // remove container at the end of the session
                                        "-e PYTHONPATH=/code/ " +                   // environment variable support
                                        "-w=/code " +                               // setting working directory
                                        "-v `pwd`/blazedemo_app:/code " +           // mount git repository to the container
                                        "blazemeter/selenium_image:latest " +       // the specific image that being used (latest image by default)
                                        "-v"                                        // verbose (for debugging purpose)
                            }
                            catch (error)
                            {
                                echo error.message
                            }
                        }
                    }
                }
            }
            post
            {
                always
                {
                    // Generate Allure Report
                    generateAllureReport()

                    // Send Slack notification
                    //sendSlackNotification()
                }
            }
        }

// Generate Allure report function
def generateAllureReport()
    {
        try
        {
            allure([
                    commandline      : '2.5.0',
                    includeProperties: false,
                    jdk              : '',
                    properties       : [[key: 'allure.tests.management.pattern', value: 'http://tms.company.com/%s']],
                    reportBuildPolicy: 'ALWAYS',
                    results          : [[path: 'blazedemo_app/allure-results']]
            ])
        }
        catch (error)
        {
            error.message
        }
    }

// Send Slack notification function
